### ISSUE TITLE
[bug] 博客的博文页面右上角不停弹出消息框

### ISSUE THREAD

**Issue by HankXu** [liuxianan/liuxianan.github.io#3]
## 问题描述

进入文章页面之后右上角会不停弹出红色的小消息框。控制台输出以下内容

![image](https://user-images.githubusercontent.com/12154343/77087397-0acdd680-6a3e-11ea-8f20-63a17df4b46d.png)

![image](https://user-images.githubusercontent.com/12154343/77088242-22f22580-6a3f-11ea-843f-5a3d2ebfa91f.png)

## 访问环境

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36

## 备注

同样系统环境下，safari 表现正常

**Comment by sxei** [comment]
你好，非常感谢你的反馈，但是，我这边显示同样的系统，同样的Chrome版本，没有这个现象，会不会是你装了什么插件导致的？

**Comment by HankXu** [comment]
确实是，在无痕模式下是正常的，不好意思哈～我把 issue 关掉😅
